# This actions.yml provides caching, check out, and building for CMake-based
# packages, and is intended for use with the build-nceplibs Action.
# Alex Richert, April 2024
name: 'cache-checkout-build'
description: 'Cache, check out, and build CMake package'

inputs:
  package-name:
    required: true
  package-org:
    required: true
  git-ref:
    default: develop
  cmake-args:
    default: ""
  repo-cache:
    description: 'Cache built packages through "actions/cache"'
    default: false
  cache-immediately:
    description: 'Save cache immediately (at end of action step rather than end of workflow)'
    default: false
  root-path:
    default: ${{ github.workspace }}/nceplibs
  key-prefix:
    description: 'String to prepend to cache key (for, e.g., compiler tracking)'
    default: ""
  key-suffix:
    description: 'String to append to cache key (for, e.g., dependency tracking)'
    default: ""
  nproc:
    description: 'Number of make processes'
    default: 2
  submodules:
    description: 'Checkout with submodules'
    default: true

outputs:
  cache-hit:
    description: "Cache was hit (boolean)"
    value: ${{ steps.check-cache-hit.outputs.cachehit }}

runs:
  using: "composite"
  steps:
  
    - name: "Cache setup for '${{ inputs.package-name }}'"
      id: cache-step
      uses: actions/cache@v4
      if: ${{ inputs.repo-cache == 'true' && inputs.cache-immediately == 'false' }}
      with:
        path: ${{ inputs.root-path }}/${{ inputs.package-name }}
        key: ${{ inputs.key-prefix }}${{ inputs.package-name }}-${{ inputs.git-ref }}-${{ inputs.cmake-args }}${{ inputs.key-suffix }}

    - name: "Restore cache for '${{ inputs.package-name }}'"
      id: cache-restore-step
      uses: actions/cache/restore@v4
      if: ${{ inputs.repo-cache == 'true' && inputs.cache-immediately == 'true' }}
      with:
        path: ${{ inputs.root-path }}/${{ inputs.package-name }}
        key: ${{ inputs.key-prefix }}${{ inputs.package-name }}-${{ inputs.git-ref }}-${{ inputs.cmake-args }}${{ inputs.key-suffix }}

    - name: "Check out '${{ inputs.package-name }}'"
      uses: actions/checkout@v4
      if: ${{ steps.cache-step.outputs.cache-hit != 'true' && steps.cache-restore-step.outputs.cache-hit != 'true' }}
      with:
        repository: ${{ inputs.package-org }}/${{ inputs.package-name }}
        path: ${{ inputs.root-path }}/src/${{ inputs.package-name }}
        ref: ${{ inputs.git-ref }}
        submodules: ${{ inputs.submodules }}

    - name: "Build '${{ inputs.package-name }}'"
      if: ${{ steps.cache-step.outputs.cache-hit != 'true' && steps.cache-restore-step.outputs.cache-hit != 'true' }}
      shell: bash
      run: |
        cd ${{ inputs.root-path }}/src/${{ inputs.package-name }}
        cmake -B ncepbuild -DALLOW_IN_SOURCE_BUILD=ON -DBUILD_TESTING=OFF -DCMAKE_INSTALL_PREFIX=${{ inputs.root-path }}/${{ inputs.package-name }} ${{ inputs.cmake-args }}
        cmake --build ncepbuild --parallel ${{ inputs.nproc }}
        cmake --install ncepbuild

    - name: "Record whether cache was used"
      shell: bash
      id: check-cache-hit
      run: |
        if [ "${{ steps.cache-step.outputs.cache-hit }}" = "true" ] || [ "${{ steps.cache-restore-step.outputs.cache-hit }}" = "true" ]; then
          echo "cachehit=true" >> $GITHUB_OUTPUT
        else
          echo "cachehit=false" >> $GITHUB_OUTPUT
        fi

    - name: "Save cache for '${{ inputs.package-name }}'"
      uses: actions/cache/save@v4
      if: ${{ inputs.repo-cache == 'true' && inputs.cache-immediately == 'true' && steps.cache-restore-step.outputs.cache-hit != 'true' }}
      with:
        path: ${{ inputs.root-path }}/${{ inputs.package-name }}
        key: ${{ inputs.key-prefix }}${{ inputs.package-name }}-${{ inputs.git-ref }}-${{ inputs.cmake-args }}${{ inputs.key-suffix }}
